export const SALE_REPORT_REQUEST = "SALE_REPORT_REQUEST";
export const SALE_REPORT_SUCCESS = "SALE_REPORT_SUCCESS";
export const SALE_REPORT_FAIL = "SALE_REPORT_FAIL";
export const SALE_REPORT_RESET = "SALE_REPORT_RESET";
