export const SALE_LIST_REQUEST = "SALE_LIST_REQUEST";
export const SALE_LIST_SUCCESS = "SALE_LIST_SUCCESS";
export const SALE_LIST_FAIL = "SALE_LIST_FAIL";
export const SALE_LIST_RESET = "SALE_LIST_RESET";

export const SALE_CREATE_REQUEST = "SALE_CREATE_REQUEST";
export const SALE_CREATE_SUCCESS = "SALE_CREATE_SUCCESS";
export const SALE_CREATE_FAIL = "SALE_CREATE_FAIL";
export const SALE_CREATE_RESET = "SALE_CREATE_RESET";

export const SALE_DETAIL_REQUEST = "SALE_DETAIL_REQUEST";
export const SALE_DETAIL_SUCCESS = "SALE_DETAIL_SUCCESS";
export const SALE_DETAIL_FAIL = "SALE_DETAIL_FAIL";
export const SALE_DETAIL_RESET = "SALE_DETAIL_RESET";

export const SALE_EDIT_REQUEST = "SALE_EDIT_REQUEST";
export const SALE_EDIT_SUCCESS = "SALE_EDIT_SUCCESS";
export const SALE_EDIT_FAIL = "SALE_EDIT_FAIL";
export const SALE_EDIT_RESET = "SALE_EDIT_RESET";

export const SALE_DELETE_REQUEST = "SALE_DELETE_REQUEST";
export const SALE_DELETE_SUCCESS = "SALE_DELETE_SUCCESS";
export const SALE_DELETE_FAIL = "SALE_DELETE_FAIL";
export const SALE_DELETE_RESET = "SALE_DELETE_RESET";
