# Generated by Django 4.0.2 on 2022-03-15 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_sale_saleitem_remove_orderitem_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleitem',
            old_name='item',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='item_code',
            new_name='product_code',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='item_name',
            new_name='product_name',
        ),
    ]
