# Generated by Django 4.0.2 on 2022-03-15 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_rename_item_saleitem_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleitem',
            old_name='amount',
            new_name='price',
        ),
    ]
