# Generated by Django 4.0.2 on 2022-03-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'admin'), ('creator', 'creator'), ('sale', 'sale')], max_length=8, null=True),
        ),
    ]
