# Generated by Django 4.0.2 on 2022-03-02 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('created_at',), 'verbose_name': 'User'},
        ),
    ]
