# Generated by Django 4.0.2 on 2022-03-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('salesman', 'salesman'), ('manager', 'manager')], max_length=8, null=True),
        ),
    ]
